;;; init-keybindings.el --- Evil and leader keybindings -*- lexical-binding: t; -*-

;;; Code:

(with-eval-after-load 'evil
  (defvar zhq/leader-map (make-sparse-keymap)
    "Personal leader keymap.")

  (define-key evil-normal-state-map (kbd "SPC") zhq/leader-map)
  (define-key evil-motion-state-map (kbd "SPC") zhq/leader-map)
  (define-key evil-visual-state-map (kbd "SPC") zhq/leader-map)

  (evil-define-key 'insert 'global (kbd "j") #'zhq/evil-insert-j)
  (evil-define-key 'insert 'global (kbd "k") #'zhq/evil-insert-k)

  (evil-define-key 'normal 'global (kbd "C-h") #'windmove-left)
  (evil-define-key 'normal 'global (kbd "C-j") #'windmove-down)
  (evil-define-key 'normal 'global (kbd "C-k") #'windmove-up)
  (evil-define-key 'normal 'global (kbd "C-l") #'windmove-right)
  (evil-define-key 'normal 'global (kbd "]d") #'zhq/flymake-goto-next-error)
  (evil-define-key 'normal 'global (kbd "[d") #'zhq/flymake-goto-prev-error)
  (evil-define-key 'normal 'global (kbd "gl") #'zhq/flymake-show-diagnostic)
  (evil-define-key 'normal 'global (kbd "K") #'eldoc-doc-buffer)
  (evil-define-key 'normal 'global (kbd "gr") #'xref-find-references)
  (evil-define-key 'normal 'global (kbd "gd") #'xref-find-definitions)
  (evil-define-key 'normal 'global (kbd "gD") #'eglot-find-declaration)
  (evil-define-key 'normal 'global (kbd "gi") #'eglot-find-implementation)

  (keymap-set zhq/leader-map "SPC" #'execute-extended-command)
  (keymap-set zhq/leader-map "/" #'zhq/comment-line-or-region)
  (keymap-set zhq/leader-map "b b" #'consult-buffer)
  (keymap-set zhq/leader-map "b k" #'kill-current-buffer)
  (keymap-set zhq/leader-map "b n" #'next-buffer)
  (keymap-set zhq/leader-map "b p" #'previous-buffer)
  (keymap-set zhq/leader-map "b D" #'kill-some-buffers)
  (keymap-set zhq/leader-map "c a" #'eglot-code-actions)
  (keymap-set zhq/leader-map "c e" #'zhq/eslint-fix-file)
  (keymap-set zhq/leader-map "c f" #'zhq/format-buffer)
  (keymap-set zhq/leader-map "c l" #'eglot)
  (keymap-set zhq/leader-map "c r" #'eglot-rename)
  (keymap-set zhq/leader-map "e c" #'zhq/open-emacs-config)
  (keymap-set zhq/leader-map "e d" #'zhq/find-dotfiles)
  (keymap-set zhq/leader-map "e e" #'dired-jump)
  (keymap-set zhq/leader-map "f b" #'consult-buffer)
  (keymap-set zhq/leader-map "f f" #'project-find-file)
  (keymap-set zhq/leader-map "f F" #'find-file)
  (keymap-set zhq/leader-map "f r" #'consult-recent-file)
  (keymap-set zhq/leader-map "f w" #'consult-ripgrep)
  (keymap-set zhq/leader-map "f m" #'consult-mark)
  (keymap-set zhq/leader-map "g b" #'magit-blame-addition)
  (keymap-set zhq/leader-map "g d" #'magit-diff)
  (keymap-set zhq/leader-map "g g" #'magit-status)
  (keymap-set zhq/leader-map "g l" #'magit-log-current)
  (keymap-set zhq/leader-map "h f" #'describe-function)
  (keymap-set zhq/leader-map "h k" #'describe-key)
  (keymap-set zhq/leader-map "h v" #'describe-variable)
  (keymap-set zhq/leader-map "l a" #'eglot-code-actions)
  (keymap-set zhq/leader-map "l d" #'zhq/flymake-show-buffer-diagnostics)
  (keymap-set zhq/leader-map "l D" #'zhq/flymake-show-project-diagnostics)
  (keymap-set zhq/leader-map "l f" #'zhq/format-buffer)
  (keymap-set zhq/leader-map "l i" #'consult-imenu)
  (keymap-set zhq/leader-map "l l" #'eglot)
  (keymap-set zhq/leader-map "l r" #'eglot-rename)
  (keymap-set zhq/leader-map "l R" #'eglot-reconnect)
  (keymap-set zhq/leader-map "l s" #'consult-imenu)
  (keymap-set zhq/leader-map "p f" #'project-find-file)
  (keymap-set zhq/leader-map "p p" #'project-switch-project)
  (keymap-set zhq/leader-map "p s" #'consult-ripgrep)
  (keymap-set zhq/leader-map "p c" #'project-compile)
  (keymap-set zhq/leader-map "p d" #'project-dired)
  (keymap-set zhq/leader-map "p e" #'project-eshell)
  (keymap-set zhq/leader-map "p r" #'project-query-replace-regexp)
  (keymap-set zhq/leader-map "q q" #'save-buffers-kill-terminal)
  (keymap-set zhq/leader-map "s g" #'consult-git-grep)
  (keymap-set zhq/leader-map "s s" #'consult-line)
  (keymap-set zhq/leader-map "t d" #'zhq/project-dev)
  (keymap-set zhq/leader-map "t n" #'zhq/project-run-package-script)
  (keymap-set zhq/leader-map "t t" #'project-eshell)
  (keymap-set zhq/leader-map "t T" #'zhq/project-test)
  (keymap-set zhq/leader-map "w d" #'delete-window)
  (keymap-set zhq/leader-map "w h" #'windmove-left)
  (keymap-set zhq/leader-map "w j" #'windmove-down)
  (keymap-set zhq/leader-map "w k" #'windmove-up)
  (keymap-set zhq/leader-map "w l" #'windmove-right)
  (keymap-set zhq/leader-map "w o" #'delete-other-windows)
  (keymap-set zhq/leader-map "w s" #'split-window-below)
  (keymap-set zhq/leader-map "w v" #'split-window-right)
  (keymap-set zhq/leader-map "w =" #'balance-windows)

  (evil-define-operator zhq/evil-comment-or-uncomment (beg end)
    "Toggle comments from BEG to END."
    (interactive "<r>")
    (comment-or-uncomment-region beg end))

  (evil-define-key 'normal 'global (kbd "gc") #'zhq/evil-comment-or-uncomment)
  (evil-define-key 'visual 'global (kbd "gc") #'zhq/evil-comment-or-uncomment)

  (evil-define-key 'normal 'global (kbd "g;") #'goto-last-change)
  (evil-define-key 'normal 'global (kbd "g,") #'goto-last-change-reverse))

(provide 'init-keybindings)

;;; init-keybindings.el ends here
